language: node_js
node_js: '6'
env:
  global:
  - REPO_SLUG=YanzheL/config-generator
  - secure: "iWY56cCywwPaikVMbt79GwQemWgv9srq4oQokffuoW5C/4iu6oFLiKdhAKlqWTojO6RKxVXnvAf7uVnxdmB6xiMbdiZ5xI9RNU5BWm14ZEZmEn//la8f4zOrlXZ8UNZC7uSkDxVxlnK8U+7rmEUaa1aC8bIhngJaJlRabduqKvSsw/RcZUQugT3dSqh6tU3Ig6a2AQhk7eJEAVI52rw1TsVWM/73qs+uIyEOEx5J5tTVx2XL5dAjELI+pMIqkDOyAABCJa3gqqCFoHu51bAONNdAB5EuaXwTiktnIQ+fctT7H+U9TkZntcDsx4e1ThBAxmhajn07VlyG5ZzmPRszM6ebAZeabPr/RafWcp2WOoEcWW4CjbgLoBnuHKTLDA3TDipO0LeGJmPFQghoCdtIjftkWEKr0N159h/vzEoUNe1fueSwcZ9+hTwIcOQpKjl503EihI9tGbtQW2jHr2G9StMTPHR5dvrDcDdaxXWIRoDg4dSlTQAvQKxAYpTZOW7OeKdTXAqc+iMFRW4zpIwS7u2oxDGLb3UZbnAwpOmdIvuand0LJs7/BA4spfucQdCJfVWu0LWRREgUeRHe8jYBD+Acfy5/91Va522mrmWbfQqku/gXhsPPYLzHlYbOxMYpzTOKmBen+zKnBJbcl8bu6xFFit1syq0O93IDZLtkDyk="
script:
- npm run lint
- npm test
- npm run build
after_success:
- "./scripts/deploy-to-gh-pages.sh"
